name: CI
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 conviso-sast:
   runs-on: ubuntu-latest
   container:
     image: convisoappsec/flowcli
     env:
       FLOW_API_KEY:  ${{secrets.FLOW_API_KEY}}
       FLOW_PROJECT_CODE: "adt02mMRg5BXbEDy"
   steps:
   - uses: actions/checkout@v2

   - name: Run SAST
     run: conviso sast run
